version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: vDINb2cweXaUZzQ76BAudM4PsHWchmC7xtD47jB2nkDK81O7RRwm0dli37+JKVK1
before_build:
- cmd: nuget restore PhotoArtSystem/PhotoArtSystem.sln
build:
  project: PhotoArtSystem/PhotoArtSystem.sln
  parallel: true
  verbosity: minimal
test:
  assemblies: PhotoArtSystem\Tests\PhotoArtSystem.Tests.UnitTests\bin\Debug\PhotoArtSystem.Tests.UnitTests.dll
after_test:
- cmd: "PhotoArtSystem\\packages\\OpenCover.4.6.519\\tools\\OpenCover.Console.exe -register:user -filter:\"+[*]*\" -target:\"PhotoArtSystem\\packages\\NUnit.ConsoleRunner.3.6.1\\tools\\nunit3-console.exe\" -targetargs:\"/domain:single PhotoArtSystem\\Tests\\PhotoArtSystem.Tests.UnitTests\\bin\\Debug\\PhotoArtSystem.Tests.UnitTests.dll\" -output:coverage.xml \nPhotoArtSystem\\packages\\coveralls.io.1.3.4\\tools\\coveralls.net.exe --opencover coverage.xml"